import {CronGenComponent} from './cron-gen.component';
import {CronGenService} from './cron-gen.service';
import {CronGenTimeSelect} from './cron-gen-time-select.component';

angular.module('angular-cron-gen', ['pascalprecht.translate'])
    .config(function ($translateProvider) {
        $translateProvider
            .translations('en', {
                'MINUTES': 'Minutes',
                'HOURLY': 'Hourly',
                'DAILY': 'Daily',
                'WEEKLY': 'Weekly',
                'MONTHLY': 'Monthly',
                'YEARLY': 'Yearly',
                'ADVANCED': 'Advanced',
                'EVERY': 'Every',
                'MINUTE': 'minute(s)',
                'ON_SECOND': 'on second',
                'HOUR_ON_MINUTE': 'hour(s) on minute',
                'AND_SECOND': 'and second',
                'DAY_AT': 'day(s) at',
                'EVERY_WEEK_WORKING_DAY': 'Every week day (Monday through Friday) at',
                'MONDAY': 'Monday',
                'TUESDAY': 'Tuesday',
                'WEDNESDAY': 'Wednesday',
                'THURSDAY': 'Thursday',
                'FRIDAY': 'Friday',
                'SATURDAY': 'Saturday',
                'SUNDAY': 'Sunday',
                'START_TIME': 'Start time',
                'ON_THE': 'On the',
                'OF_EVERY': 'of every',
                'MONTHS_AT': 'month(s) at',
                'AT': 'at',
                'OF': 'of',
                'CRON_EXPRESSION': 'Cron Expression',
                'MORE_DETAILS': 'More details about how to create these expressions can be found',
                'HERE': 'here',
                'LAST_DAY': 'Last day',
                'LAST_WEEKDAY': 'Last Weekday',
                'FIRST_WEEKDAY': 'First Weekday',
                'DAY': 'Day',
                'FIRST_PREFIX': 'st',
                'SECOND_PREFIX': 'nd',
                'THIRD_PREFIX': 'rd',
                'CARDINAL_PREFIX': 'th',
                'FIRST': 'First',
                'SECOND': 'Second',
                'THIRD': 'Third',
                'FOURTH': 'Fourth',
                'FIFTH': 'Fifth',
                'LAST': 'Last',
                'JANUARY': 'January',
                'FEBRUARY': 'February',
                'MARCH': 'March',
                'APRIL': 'April',
                'MAY': 'May',
                'JUNE': 'June',
                'JULY': 'July',
                'AUGUST': 'August',
                'SEPTEMBER': 'September',
                'OCTOBER': 'October',
                'NOVEMBER': 'November',
                'DECEMBER': 'December'
            })
            .translations('it', {
                'MINUTES': 'Minuti',
                'HOURLY': 'Orario',
                'DAILY': 'Giornaliero',
                'WEEKLY': 'Settimanale',
                'MONTHLY': 'Mensile',
                'YEARLY': 'Annuale',
                'ADVANCED': 'Avanzato',
                'EVERY': 'Ogni',
                'MINUTE': 'minuto/i',
                'ON_SECOND': 'al secondo',
                'HOUR_ON_MINUTE': 'ora/e al minuto',
                'AND_SECOND': 'e secondi',
                'DAY_AT': 'giorno/i alle',
                'EVERY_WEEK_WORKING_DAY': "Ogni giorno della settimana (dal Lunedi' al Venerdi') alle",
                'MONDAY': "Lunedi'",
                'TUESDAY': "Martedi'",
                'WEDNESDAY': "Mercoledi'",
                'THURSDAY': "Giovedi'",
                'FRIDAY': "Venerdi'",
                'SATURDAY': 'Sabato',
                'SUNDAY': 'Domenica',
                'START_TIME': 'Inizio alle',
                'ON_THE': 'Il',
                'OF_EVERY': 'di ogni',
                'MONTHS_AT': 'mese/i il',
                'AT': 'il',
                'OF': 'di',
                'CRON_EXPRESSION': 'Sintassi Cron',
                'MORE_DETAILS': 'Maggiori informazioni sulla sintassi Cron li potete trovare',
                'HERE': 'qui',
                'LAST_DAY': 'Ultimo giorno',
                'LAST_WEEKDAY': 'Fine settimana',
                'FIRST_WEEKDAY': 'Inizio settimana',
                'DAY': 'Giorno',
                'FIRST_PREFIX': '',
                'SECOND_PREFIX': '',
                'THIRD_PREFIX': '',
                'CARDINAL_PREFIX': '',
                'FIRST': 'Primo',
                'SECOND': 'Secondo',
                'THIRD': 'Terzo',
                'FOURTH': 'Quarto',
                'FIFTH': 'Quinto',
                'LAST': 'Ultimo',
                'JANUARY': 'Gennaio',
                'FEBRUARY': 'Febbraio',
                'MARCH': 'Marzo',
                'APRIL': 'Aprile',
                'MAY': 'Maggio',
                'JUNE': 'Giugno',
                'JULY': 'Luglio',
                'AUGUST': 'Agosto',
                'SEPTEMBER': 'Settembre',
                'OCTOBER': 'Ottobre',
                'NOVEMBER': 'Novembre',
                'DECEMBER': 'Dicembre'
            })
            .translations('de', {
                'MINUTES': 'Minütlich',
                'HOURLY': 'Stündlich',
                'DAILY': 'Täglich',
                'WEEKLY': 'Wöchentlich',
                'MONTHLY': 'Monatlich',
                'YEARLY': 'Jährlich',
                'ADVANCED': 'Cron Ausdruck',
                'EVERY': 'Jede(n)',
                'MINUTE': 'Minute(n)',
                'ON_SECOND': 'auf Sekunde',
                'HOUR_ON_MINUTE': 'Stunde(n) auf Minute',
                'AND_SECOND': 'und SeKunde',
                'DAY_AT': 'Tag(e) um',
                'EVERY_WEEK_WORKING_DAY': "Jeden Wochentag (Montag bis Freitag) um",
                'MONDAY': "Montag'",
                'TUESDAY': "Dienstag'",
                'WEDNESDAY': "Mittwoch'",
                'THURSDAY': "Donnerstag'",
                'FRIDAY': "Freitag'",
                'SATURDAY': 'Samstag',
                'SUNDAY': 'Sonntag',
                'START_TIME': 'Startzeit',
                'ON_THE': 'Am',
                'OF_EVERY': 'an jedem',
                'MONTHS_AT': 'Monat(e) um',
                'AT': 'um',
                'OF': 'im',
                'CRON_EXPRESSION': 'Cron Ausdruck',
                'MORE_DETAILS': 'Weitere Informationen zum Erstellen dieser Ausdrücke finden Sie ',
                'HERE': 'hier',
                'LAST_DAY': 'letzter Tag',
                'LAST_WEEKDAY': 'letzter Wochentag',
                'FIRST_WEEKDAY': 'erster Wochentag',
                'DAY': 'Tag',
                'FIRST_PREFIX': '',
                'SECOND_PREFIX': '',
                'THIRD_PREFIX': '',
                'CARDINAL_PREFIX': '',
                'FIRST': 'First',
                'SECOND': 'Second',
                'THIRD': 'Third',
                'FOURTH': 'Fourth',
                'FIFTH': 'Fifth',
                'LAST': 'Last',
                'JANUARY': 'January',
                'FEBRUARY': 'February',
                'MARCH': 'March',
                'APRIL': 'April',
                'MAY': 'May',
                'JUNE': 'June',
                'JULY': 'July',
                'AUGUST': 'August',
                'SEPTEMBER': 'September',
                'OCTOBER': 'October',
                'NOVEMBER': 'November',
                'DECEMBER': 'December'
            });
    })
    .service('cronGenService', CronGenService)
    .component('cronGenTimeSelect', {
        bindings: {
            isDisabled: '<',
            onChange: '&',
            isRequired: '<',
            model: '=',
            selectClass: '<',
            use24HourTime: '<',
            hideSeconds: '<',
            namePrefix: '@'
        },
        templateUrl: 'angular-cron-gen/cron-gen-time-select.html',
        controller: CronGenTimeSelect
    })
    .component('cronGen', {
        bindings: {
            ngModel: '=',
            ngDisabled: '<',
            options: '<',
            cronFormat: '@',
            templateUrl: '@',
            name: '@'
        },
        require: {
            ngModelCtrl: 'ngModel',
            ngDisabledCtrl: '?ngDisabled',
            formCtrl: '^?form'
        },
        templateUrl($attrs) {
            'ngInject';
            return $attrs.templateUrl || 'angular-cron-gen/cron-gen.html';
        },
        controller: CronGenComponent
    });
